<?php

namespace StoryBundle\Repository;

/**
 * HintRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HintRepository extends \Doctrine\ORM\EntityRepository
{
}
