<?php

namespace StoryBundle\Repository;

/**
 * ProgressionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProgressionRepository extends \Doctrine\ORM\EntityRepository
{
}
