<?php

namespace StoryBundle\Repository;

/**
 * StoryPartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StoryPartRepository extends \Doctrine\ORM\EntityRepository
{
}
